### ISSUE TITLE
[Question] Multi column layout with auto-sizing elements but the rows are filled

### ISSUE THREAD

**Issue by chosa91** [nemecek-filip/CompositionalDiffablePlayground.ios#1]
Is it possible with the Compositional Layout to define a layout which fulfills all the following criteria:
- Multi-column
- The cells are auto-sizing
- Each cell in the row will fit into the row (picks up its largest possible size)

**Comment by nemecek-filip** [comment]
If I understand the question correctly, this example should be available on the main screen. The bottom sections are responsive and depending on the count, they always take the entire width.

This method calculates the fractional width:

```swift
 private func calculateResponsiveFractionalWidth(itemCount: Int, maxVisibleCount: Int) -> CGFloat {
        let fractionalWidthToFillSpace: CGFloat
        if itemCount < maxVisibleCount {
            let half = (Double(itemCount) / 2)
            fractionalWidthToFillSpace = CGFloat(1 / half.rounded(.up))
        } else {
            fractionalWidthToFillSpace = 0.25
        }
        
        return fractionalWidthToFillSpace
    }
```
If this is not what you want, could you maybe attach an image or screenshot of what you want to achieve? :-) I will be happy to help.

**Comment by chosa91** [comment]
Thanks for the quick reply, unfortunately the problem is not that simple.
Per row, the height should be the size of the highest cell.
We were able to solve it with Custom FlowLayout, but I would be interested to see if Compositional Layout can do that as well.

The expected behavior is something like this:
```
    ┌─────────────┐ ┌─────────────┐
    │┌───────────┐│ │┌───────────┐│
    ││  Cell 1   ││ ││  Cell 2   ││
    │└───────────┘│ │└───────────┘│
    │             │ │┌───────────┐│
    │             │ ││  Button   ││
    │             │ │└───────────┘│
    └─────────────┘ └─────────────┘
    ┌─────────────┐ ┌─────────────┐
    │┌───────────┐│ │┌───────────┐│
    ││  Cell 3   ││ ││  Cell 4   ││
    │└───────────┘│ │└───────────┘│
    └─────────────┘ └─────────────┘
    ┌─────────────┐ ┌─────────────┐
    │┌───────────┐│ │┌───────────┐│
    ││  Cell 5   ││ ││  Cell 6   ││
    │└───────────┘│ │└───────────┘│
    │┌───────────┐│ │             │
    ││  Button   ││ │             │
    │└───────────┘│ │             │
    └─────────────┘ └─────────────┘
```

**Comment by nemecek-filip** [comment]
Thanks for the super clear visualization. I think this is possible with Compositional Layout but you need to access datasource when defining the layout to know whether to show the button cell. 

I think I am going to try this layout too, because it is quite different from those available.

**Comment by nemecek-filip** [comment]
After some thinking the above idea might not work, because you cannot customize layout definitions per items, only per section. However if the `Button` could be part of the cell (that you could toggle to be visible or not), then I think the layout is doable with CL.

**Comment by chosa91** [comment]
Yeah, my labeling isn't right, here is a better version of the layout expectation:
```
                 GIVEN                             EXPECTED
    ┌─────────────┐ ┌─────────────┐     ┌─────────────┐ ┌─────────────┐
    │Cell with    │ │1 line txt   │     │Cell with    │ │1 line txt   │
    │multiline    │ └─────────────┘     │multiline    │ │             │
    │text         │                     │text         │ │             │
    └─────────────┘                     └─────────────┘ └─────────────┘
    ┌─────────────┐ ┌─────────────┐     ┌─────────────┐ ┌─────────────┐
    │Two line of  │ │Lorem ipsum  │     │Two line of  │ │Lorem ipsum  │
    │text         │ │dolor sit    │     │text         │ │dolor sit    │
    └─────────────┘ │amet,        │     │             │ │amet,        │
                    │consectetur  │     │             │ │consectetur  │
                    │adipiscing   │     │             │ │adipiscing   │
                    │elit.        │     │             │ │elit.        │
                    │Phasellus    │     │             │ │Phasellus    │
                    │congue quis  │     │             │ │congue quis  │
                    │mi ut tempus.│     │             │ │mi ut tempus.│
                    │Sed posuere  │     │             │ │Sed posuere  │
                    │nibh lacus,  │     │             │ │nibh lacus,  │
                    │eget gravida │     │             │ │eget gravida │
                    │tortor       │     │             │ │tortor       │
                    │dapibus      │     │             │ │dapibus      │
                    │vestibulum.  │     │             │ │vestibulum.  │
                    └─────────────┘     └─────────────┘ └─────────────┘
```

I've played with `interItemSpacing` & `edgeSpacing`, but none of them worked as I expected. My cells are auto-sized but didn't fill the remaining space in the group

**Comment by nemecek-filip** [comment]
Did you try to use the `fractionalHeight`? I think this should stretch the cells to fill the layout groups.

**Comment by chosa91** [comment]
Yes I did, with no luck, since when I set `fractionalHeight` as `itemSize`, the cells will use the group's size which is `.estimated(44)`, but in this case they will use 44 and won't grow any further. 
Although it is possible that I configured it incorrectly.
Here is one my [playground](https://gist.github.com/chosa91/c11f1c44df72be6507f2feac13a06aed), I think it'll make much more sense to speak over real-code.

**Comment by nemecek-filip** [comment]
I have to say, you are right, this is quite challenge 🤔  Just tried various modifications to your playground but so far nothing that produces the desired result

**Comment by LeeKahSeng** [comment]
After playing around with @chosa91  sample code for a couple of hours, I think most probably this is a limitation of the framework.  Let’s consider the following scenarios (note that I am using 300 as estimated height):

**Scenario 1:**
- `item` have `.estimated(300)` as `heightDimension`
- `innerGroup` have `.estimated(300)` as `heightDimension`
- **Result**: Cell is auto-sizing, but not taking up the entire height.
- **Speculation**: UIKit calculates the height of all the items within `innerGroup`, then `innerGroup` takes the largest item’s height as its height. 

**Scenario 2:**
- `item` have `.fractionalHeight(1.0)` as `heightDimension`
- `innerGroup` have `.estimated(300)` as `heightDimension`
- **Result**: Cell is not auto-sizing, but taking up the entire height.
- **Speculation**: Since item have fractional height, UIKit will need some other information to determine the actual cell’s height. Therefore, it will use the `innerGroup`’s estimated height (300) we provided as the item’s height, causing all cells to have the same height.

If the speculation in both scenarios is correct, then trying to achieve what we want is like asking UIKit to get the largest item’s height without calculating the item’s height, which is not even possible.

That’s why I think most probably this is an UIKit limitation.

Feel free to let me know what you think.

PS: I even try using `NSCollectionLayoutGroup.custom` but still no luck.

**Comment by nemecek-filip** [comment]
@LeeKahSeng nice findings! Thanks for trying this out. Looks like the declarative approach has its limits.

You could theoretically calculate the height of the cell manually (like asking UIKit for height of text with certain font + margins) and then maybe set the height as absolute of the max of the 3 items in the same row. But even writing it here feels crazy :D

**Comment by LeeKahSeng** [comment]
@nemecek-filip yup, calculating the cell size manually should be possible, provided we have all the cell's content upfront. I can foresee there will be some complicated logic involve, and I don't think I want to maintain this kind of source code. 🙈

**Comment by chosa91** [comment]
Since we can align our items horizontally and vertically inside a group with `flexible` `edgeSpace`s, 
I thought I can achieve that the items will expand to their container's edges when I set `edgeSpacing`on the group on top and bottom to a fixed amount, but it didn't worked :'(
```swift
group.edgeSpacing = NSCollectionLayoutEdgeSpacing(leading: nil, top: .fixed(0), trailing: nil, bottom: .fixed(0))
```

**Comment by chosa91** [comment]
I'm closing this topic since we've finally got an official solution 😃 
https://developer.apple.com/documentation/uikit/nscollectionlayoutdimension/4173072-uniformacrosssiblings?language=objc
